chicagobusiness/urls.py
from django.contrib import admin
from django.urls import path, include, re_path, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('morelia/', admin.site.urls),
    path('', include('jump_app.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jump_app/urls.py
from django.urls import path, include, re_path
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import TemplateView

from . import views
app_name = 'jump'

urlpatterns = [
    path('', views.home_view, name='home'),
    path('thankyou/', views.request_services, name='thankyou'),
    path('sitemap.xml', views.site_map, name='sitemap'),
    path('robots.txt', TemplateView.as_view(template_name="jump_app/robots.txt", content_type="text/plain"),
         name="robots_file")

]

jump_app/models.py
from django.db import models

# Create your models here.

jump_app/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings


def home_view(request):
    return render(request, 'jump_app/home.html')


def site_map(request):
    return render(request, 'jump_app/sitemap.xml', content_type='text/xml')



def request_services(request):
    get_manual_address = request.POST.get('manual_address')
    phone_number = request.POST.get('phone')
    lengua = request.POST.get('lengua')

    direccion = get_manual_address
    phone_number = ' Phone Number: {}'.format(str(phone_number))
    msg = direccion + phone_number + " : {}".format(lengua)

    email_user = 'silvanovaldez90@yahoo.com'

    send_mail('jumpstartcarservice', 'Bienvenido!', settings.EMAIL_HOST_USER, [email_user], html_message=msg,
              fail_silently=False)
    return render(request, 'jump_app/thankyou.html', {'lan': 'english', 'total': '60'})

jump_app/templates/jump_app/sitemap.html
<!DOCTYPE html>
{% extends 'jump_app/home.html' %}

{% block body_block %}

    <div class="jumbotron">
                                <a href="{% url 'jump:home'%}">Jump Start Car Service</a>
        <br>

    </div>


{% endblock %}

jump_app/templates/jump_app/thankyou.html
<!DOCTYPE html>
{% extends 'jump_app/home.html' %}
{% block body_block %}

    <img src="https://chicagocarhelp.s3.us-east-2.amazonaws.com/jumpstart_thanks.jpg" alt="" style="width: 100%; height: auto">

        <div class="container" align="center">
            <h5 class="centered" style="color:#5477ff;">I will contact you in a few seconds.</h5>
            <h5 style="color:red;">If You don't get a response in 1 minute please make sure your phone number is correct</h5>

        </div>

    <div align="center">
            <h5>We accept credit/debit card, cash or Venmo</h5>
            <h5>You will be charged when your service has been completed</h5>
    </div>


{% endblock %}